language: go
go:
  - '1.11'
script:
  - GOOS=linux go build -o main
  - zip deployment.zip main
deploy:
  provider: releases
  api_key:
    secure: 700edf8ccaf0b653a044c6d47ac54b915a7b7d08
  file: 'deployment.zip'
  skip_cleanup: true
  on:
    repo: TopherSavoie/smartthings-ringalarmv2
    tags: true
