language: go
go:
  - '1.11'
script:
  - GOOS=linux go build -o main
  - zip deployment.zip main
deploy:
  provider: releases
  api_key: f01940e695050ef62b5c1330b1a8cfbcd8f72831
  file: 'deployment.zip'
  skip_cleanup: true
  on:
    repo: TopherSavoie/smartthings-ringalarmv2
    tags: true
