language: go
go:
  - '1.11'
script:
  - GOOS=linux go build -o main
  - zip deployment.zip main
deploy:
  provider: releases
  api_key: c631b2048be6e59308011b8a74eb06e73dd8b3d7
  file: 'deployment.zip'
  skip_cleanup: true
  on:
    repo: TopherSavoie/smartthings-ringalarmv2
    tags: true
